public with sharing class DemoClass1 {
        Integer a;
        Integer b;
        integer c;
        integer d;
       Public  DemoClass1(Integer x,integer y,integer z)
        {
           a=x;
           b=y;
           c=z;
        }
        public void sum()
        {
            d=a+b+c;
        }
        public void Show()
        {
            System.Debug('sum is = '+d);
        }
        
        

    
}
