/**  Purpose         :   This is the Interface of the Customer and employee purchase of order which provide discount.
  *  Created By      :    Prem Chand
  *  Created Date    :    2022/07/06
  *  Revision Logs   :    V_1.0 - Created - 2022/07/06
  **/
public interface PurchaseOrder {

  /** 
    * Created By    :    Prem Chand
    * Purpose       :    This method is Discount
    * Params        :    void
    * Return        :    Void
    **/
    Double discount();
}